### ISSUE TITLE
set-git-user interfering with `git push`

### ISSUE THREAD

**Issue by strand** [Devbootcamp/set-git-user#21]
Working with students in Phase One I noticed this strange behavior, but I wasn't able to gather much in the way of reproducibility. :-/

![screen shot 2014-09-18 at 6 05 26 pm](https://cloud.githubusercontent.com/assets/509611/4346848/b0df376a-411a-11e4-9809-4e2076d1a4b5.png)

**Comment by supertopher** [comment]
this bug as far as i can tell is not reproducible.  i'm unsure what this issue is related to, but until it crops up again i'm closing the issue.

**Comment by strand** [comment]
:+1:

**Comment by supertopher** [comment]
hi strand! i miss you! I'm a gonna to send you an email and see how you are doing!
